#MySQL configuration
spring.datasource.url=jdbc:mysql://localhost:3306/bj_pranie?verifyServerCertificate=false&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=phpmyadmin
spring.datasource.password=czekolada
password.salt=dupa

#Email
spring.mail.host=smtp.office365.com
spring.mail.port=
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=
spring.mail.properties.mail.smtp.starttls.enable=

#LOGGING
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
logging.file.max-history=10

#System configuration
holidays=false
wmCount=5
tdCount=2
#message=${INDEX_MESSAGE}